### ISSUE TITLE
Potential Improvement for the README file

### ISSUE THREAD

**Issue by SabrinaAshik** [pokarparth/ztem_simpeg#1]
I really liked how you listed a short description for each folders and notebook files! 

I think the title of the repository could be a little more discriptive.

Additionally, I think it could be useful to add:
- Installation instruction for the project
- License information to clarify how users can use and distribute the content within the repository.

**Comment by pokarparth** [comment]
Thanks for the suggestions! 

I agree with everything and I've updated the readme :)
